{% set name = "liblsl" %}
{% set version = "1.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sccn/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7410620c26f8e86ae431e7476bf685918e180bd676982a7f7a7817299c8707c5

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('liblsl', max_pin='x') }}

requirements:
  build:
    - cmake >=3.12
    - make
    - {{ compiler('cxx') }}
  host:
    - pugixml

test:
  commands:
    - lslver
    - test -f $PREFIX/include/lsl_c.h  # [unix]
    - test -f $PREFIX/include/lsl_cpp.h  # [unix]
    - if not exist %LIBRARY_INC%\\lsl_c.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\lsl_cpp.h exit 1  # [win]
    - test -f $PREFIX/lib/liblsl${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\lsl.dll exit 1  # [win]

about:
  home: https://github.com/sccn/liblsl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Multi-modal time-synched data transmission over local network
  doc_url: https://labstreaminglayer.readthedocs.io/
  dev_url: https://github.com/sccn/{{ name }}
extra:
  recipe-maintainers:
    - cboulay
    - tstenner
